### ISSUE TITLE
getAirportArrivals returns NULL for large time intervals

### ISSUE THREAD

**Issue by d-qn** [Rafael-Ayala/openSkies#1]
Hello there. Thank you for this package ! There is a weird/buggy behaviour with _getAirportArrivals_ though I think, when extending the time range I always get NULL as a result. For instance, running the line of code under returns, 11 flights:

`openSkies::getAirportArrivals(airport="LSGL", startTime="2022-07-10 00:00:00", endTime="2022-07-10 23:00:00", timeZone = "Europe/Zurich")`

However if I run the same query but with a larger time range, changing only the start time to get for instance a 10 days time range:

`openSkies::getAirportArrivals(airport="LSGL", startTime="2022-07-01 00:00:00", endTime="2022-07-10 23:00:00", timeZone = "Europe/Zurich"
)` 

Then it returns NULL "No arrivals found for the specified interval and airport."

**Comment by d-qn** [comment]
I realise now that the problem is on OpenSky network API's side, I found that: ["The given time interval must not be larger than seven days!"](https://openskynetwork.github.io/opensky-api/rest.html#departures-by-airport). I guess it should be on their side that a warning message should be issued

**Comment by Rafael-Ayala** [comment]
Thanks a lot for your interest in our package! Indeed, the limitation is coming from the API's side. But I think it should be possible to automate a workaround by automatically splitting queries for times longer than 1 week into multiple smaller queries. I will try to get around implementing that as soon as possible!

**Comment by Rafael-Ayala** [comment]
@d-qn This took longer than expected, but finally the change has been implemented!

Now intervals of any length should work fine for functions _getAirportArrivals_, _getAirportDepartures_ and _getAircraftFlights_. Additionally, _getIntervalFlights_ had a similar limitation but to intervals of 2 hours. Unlimited intervals should work fine for this function too.

I have not pushed the changes to CRAN yet since I would like to implement some other new functionalities before submitting a new version to CRAN, but you can test it by installing the development version from GitHub with:

`
devtools::install_github("Rafael-Ayala/openSkies")
`

It would be great if you could have a go at it and let me know if it works as expected! :)

**Comment by d-qn** [comment]
Sounds great, thank you ! Ok, I will take those for a test drive in the upcoming weeks and I'll let you know. Cheers!

**Comment by d-qn** [comment]
Hello. It seems to work fine by me. Is it correct that the results are not sorted (either by arrival or departure time) though ?  Not a problem at all for me, just for me to know

**Comment by Rafael-Ayala** [comment]
That's great to know! That is correct, they are not sorted as they come out. But it can be easily done if you need, with something like this (to be modified depending on the value to use for ordering and if ascending or descending order is required):
```r
flights <- openSkies::getAirportDepartures(airport="LSGL", startTime="2022-07-03 22:00:00", endTime="2022-07-17 21:00:00", timeZone = "Europe/Zurich")
arrivalTimes <- sapply(flights, `[[`, "arrival_time", simplify=TRUE)
orderedFlights <- flights[order(arrivalTimes)]
```

Hope this helps!

**Comment by d-qn** [comment]
Yes, thanks!
